name: ml_project
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10         
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pyyaml
  - boto3

  - dvc
  - dvc-s3

  - xgboost

  - mlflow

  - pip:
      - python-dotenv
      - hydra-core
      - jinja2_time
      - loguru
